version: '3.8'

services:
  python-app:
    build: 
      context: ./python
    ports:
      - "5000:5000"
    container_name: python-app
  
  node-app:
    build: 
      context: ./javascripts
    ports:
      - "3000:3000"
    container_name: node-app
  
  cpp-app:
    build: 
      context: ./cpp
    ports:
      - "4000:4000"
    container_name: cpp-app
    restart: always  # Yana bir bor ishga tushishi uchun

  # csharp-app:
  #   build:
  #     context: ./csharp
  #   ports:
  #     - "5001:5001"
  #   container_name: csharp-app
  #   restart: always  # Yana bir bor ishga tushishi uchun

  java-app:
    build: 
      context: ./java
    ports:
      - "8081:8081"
    container_name: java-app
    restart: always  # Yana bir bor ishga tushishi uchun

  go-app:
    build:
      context: ./go
    ports:
      - "8081:8081"
    container_name: go-app
    
