apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csharp-app
  template:
    metadata:
      labels:
        app: csharp-app
    spec:
      containers:
        - name: csharp-app
          image: my-docker-image:latest
          ports:
            - containerPort: 5001
