apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80  # Tashqi kirish porti
      targetPort: 5000  # Konteynerdagi port
  type: LoadBalancer
