name:  Docker Images

on:
  push:
    branches:
      - main  # main branchga push qilganda workflow ishga tushadi

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Repository'dan kodni olish
      - name: Checkout repository
        uses: actions/checkout@v3

      # Docker Hub'ga kirish
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets dan Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets dan Docker password

      # Python konteynerini yaratish va push qilish
      - name: Build and Push Python Image
        run: |
          cd server
          cd python
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/python-app:latest

      # Node.js konteynerini yaratish va push qilish
      - name: Build and Push Node.js Image
        run: |
          cd server
          cd javascripts
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      # C++ konteynerini yaratish va push qilish
      - name: Build and Push C++ Image
        run: |
          cd server
          cd cpp
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cpp-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cpp-app:latest

      # C# konteynerini yaratish va push qilish
      # - name: Build and Push C# Image
      #   run: |
      #     cd server
      #     cd csharp
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/csharp-app:latest .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/csharp-app:latest

      # Java konteynerini yaratish va push qilish
      - name: Build and Push Java Image
        run: |
          cd server
          cd java
          docker build -t ${{ secrets.DOCKER_USERNAME }}/java-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/java-app:latest

      # Go konteynerini yaratish va push qilish
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: /tmp/go-cache
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Build and Push Docker Image
        run: |
          docker build -t yourdockerhubusername/go-app:latest .
          docker push yourdockerhubusername/go-app:latest

